# Generated by Django 4.2.13 on 2024-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_id', models.IntegerField()),
                ('date', models.DateField()),
                ('cur_abbreviation', models.CharField(max_length=100)),
                ('cur_scale', models.IntegerField()),
                ('cur_name', models.CharField(max_length=100)),
                ('cur_officialRate', models.FloatField()),
            ],
        ),
    ]
